version: "3.8"

services:
  newsapi-collector:
    image: vramososuna/newsapi:latest
    container_name: newsapi-collector
    networks:
      - mongo-net
    env_file:
      - .env
    volumes:
      - ./data/newsapi:/data  # Almacena datos en el host

  gnews-collector:
    image: vramososuna/gnews:latest
    container_name: gnews-collector
    networks:
      - mongo-net
    env_file:
      - .env
    volumes:
      - ./data/gnews:/data  # Almacena datos en el host

  newsapiai-collector:
    image: vramososuna/newsapiai:latest
    container_name: newsapiai-collector
    networks:
      - mongo-net
    env_file:
      - .env
    volumes:
      - ./data/newsapiai:/data  # Almacena datos en el host
    
networks:
  mongo-net:
    external: true
