version: "3.8"

services:
  newsapi-collector:
    image: vramososuna/newsapi
    container_name: newsapi-collector
    env_file:
      - .env
    volumes:
      - raw-data:/app/data/  # Almacena datos en el host

  gnews-collector:
    image: vramososuna/gnews
    container_name: gnews-collector
    env_file:
      - .env
    volumes:
      - raw-data:/app/data/  # Almacena datos en el host

  newsapiai-collector:
    image: vramososuna/newsapiai
    container_name: newsapiai-collector
    env_file:
      - .env
    volumes:
      - raw-data:/app/data/  # Almacena datos en el host
    
networks:
  mongo-net:
    external: true

volumes:
  raw-data:
    name: raw-data
    external: true
