version: '3.8'

services:
  newsapi-worker:
    image: vramososuna/worker
    environment:
      - API_NAME=newsapi
    env_file:
      - .env
    volumes:
      - raw-data:/app/data/  # Almacena datos en el host
    networks:
      - mongo-net
      - milvus-net
    deploy:
      mode: replicated
      replicas: 0

  gnews-worker:
    image: vramososuna/worker
    environment:
      - API_NAME=gnews
    env_file:
      - .env
    volumes:
      - raw-data:/app/data/  # Almacena datos en el host
    networks:
      - mongo-net
      - milvus-net
    deploy:
      mode: replicated
      replicas: 3

  newsapiai-worker:
    image: vramososuna/worker
    environment:
      - API_NAME=newsapiai
    env_file:
      - .env
    volumes:
      - raw-data:/app/data/  # Almacena datos en el host
    networks:
      - mongo-net
      - milvus-net
    deploy:
      mode: replicated
      replicas: 3

networks:
  mongo-net:
    external: true
  milvus-net:
    external: true

volumes:
  raw-data:
    name: raw-data
    external: true


    